spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_banking
    username: bank_user
    password: Root123

jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      format_sql: true # This makes the SQL in your console pretty and readable
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
